### ISSUE TITLE
Can't unpublish a package

### ISSUE THREAD

**Issue by serk12** [pulsar-edit/ppm#121]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Hello. I've been working in a fork from a old package that it's no longer working. And now I decided to publish since it's stable I named the package auto-prettier-eslint.
But I've made some mistakes in the publishing and I can't neither publish a new version or unpublish it. All I get is ```Internal Server Error```.)

### Pulsar version

1.112.1

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Ubuntu

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

Here is more or less what I've done:

1. Publish the package from gitLab and change the name. (that is not possible)
2. Import it to github. (I think I got it published here)
3. Tried to update the read me and json. (can't do it no error description

**Comment by confused-Techie** [comment]
I've taken a look at the package and was able to determine the issue.

It seems that during one of your publications you set the `repository` (In your `package.json`) to be `https://gitlab.com/serk12/eslint-fixer-pulsar`. And apparently the backend during publication has a little to much trust in what you say the repository is. Because it set that as the package's actually repository. Except, the backend doesn't support Gitlab, so now when you try to publish or unpublish, the backend has no idea how to interact with Gitlab, so errors out when attempting to do so.

What is the repository of where this code actually lives?

**Comment by serk12** [comment]
I see, this is the good one ```https://github.com/serk12/auto-prettier-eslint```.

**Comment by confused-Techie** [comment]
@serk12 Thanks for the link.

In that case, since the repo is published under your personal user account, we don't need to do anything to confirm write access. Then I'll just need to manually update the data that's within the PPR database itself, so that this package points to the correct repo on GitHub, which will allow you to make any other additional changes you'd like.

And just to be overtly clear, are you okay with me making manual changes to your package's data within the PPR database?

**Comment by serk12** [comment]
Yes no problems. I appreciate it, since I did the mess. Thanks.

**Comment by confused-Techie** [comment]
Alright, @serk12 I've gone ahead and modified that data on the actual database.

You should now be good to push additional updates. Feel free to open this issue if the problem still persists!

**Comment by machitgarha** [comment]
I cannot unpublish the latest version of the package also: https://github.com/Gert-dev/php-ide-serenata

What should I do?

**Comment by confused-Techie** [comment]
@machitgarha I'm looking into this issue now, thanks for bringing it to my attention!

I've taken a look at the logs, and can see your initial request to unpublish has failed with a generic error message, unfortunately the logging got cutoff when logging the callstack for your request, so I can't immediately see what went wrong (plus I need to find out why they got cutoff, but I'm assuming that there is some truncation of long logs in GCP Cloud Run environments, that I don't know about).

I'll take a look and see if I can't find what happened, but if you'd like, I'd really appreciate if you could try to unpublish this version one more time, so I can see if I can get the logs, in case the truncation is an error on Google's end

**Comment by machitgarha** [comment]
@confused-Techie, does unpublishing depend on the contents of the original repo (e.g. commits)? Because I've made some changes to it regarding the version.

**Comment by confused-Techie** [comment]
@machitgarha The backend doesn't ever look at commits themselves, just permissions of a repo and tags available, and in some cases the contents. But new commits shouldn't have any effect on unpublishing a specific version.

But that's very kind, thank you

**Comment by machitgarha** [comment]
@confused-Techie, alright, I just performed an unpublish command.

**Comment by confused-Techie** [comment]
@machitgarha Thanks for sending another, but yeah the logs are still being truncated. I'll have to look into what's causing that. But let me see what I can find that may be effecting this

**Comment by confused-Techie** [comment]
@machitgarha I've made a new issue to track this specifically: https://github.com/pulsar-edit/ppm/issues/138

**Comment by machitgarha** [comment]
@confused-Techie, nice! Thanks!

**Comment by confused-Techie** [comment]
@machitgarha EDIT: https://github.com/pulsar-edit/package-backend/issues/273

Put it on the offending repo causing the issue

**Comment by machitgarha** [comment]
@confused-Techie, I see, Github automatically replaced your previous message when you transferred the issue.

**Comment by confused-Techie** [comment]
@machitgarha That's so cool, no clue it'd do that, how nifty
