### ISSUE TITLE
`ppm upgrade` doesn't work for git-installed packages without a `master` branch

### ISSUE THREAD

**Issue by savetheclocktower** [pulsar-edit/ppm#55]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I was wondering why some of my git-installed packages were able to be upgraded — both within the editor and via `ppm upgrade` — and some were not. I managed to track down what I think is the answer: `ppm upgrade` [checks a hard-coded `refs/heads/master`](https://github.com/pulsar-edit/ppm/blob/master/src/upgrade.coffee#L119), and many newer repos use `main` as the default branch.

GitHub changed the default on new repos back in 2020, but never updated `apm` accordingly.

I suppose the simplest fix would be to do `repo.getUpstreamBranch('refs/heads/main') || repo.getUpstreamBranch('refs/heads/master')`, so that’s probably what I’ll do unless someone has a better suggestion.

### Pulsar version

1.101.0-beta

### Which OS does this happen on?

🍎 macOS

### OS details

11.7.3

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

I don't expect anyone to do this, but here we go:

1. Create a GitHub repo with `main` as its default branch. Put a skeleton package in it — perhaps a sample package from the Flight Manual.
2. Install it with `ppm install [github username]/[repo name]`.
3. Land a trivial update to the package on `main`.
4. Attempt to upgrade it with `ppm upgrade [repo name]`; nothing will happen.

**Comment by savetheclocktower** [comment]
From experimentation, changing the line to

```coffeescript
sha = repo.getReferenceTarget(repo.getUpstreamBranch(repo.getHead())
```

also appears to work, but I wonder why they wouldn't have simply done that in the first place.

**Comment by confused-Techie** [comment]
> From experimentation, changing the line to
> 
> ```coffee
> sha = repo.getReferenceTarget(repo.getUpstreamBranch(repo.getHead()))
> ```
> 
> also appears to work, but I wonder why they wouldn't have simply done that in the first place.

This looks like a fantastic solution! And if that works we should go for it.

No clue why it wouldn't be used originally, but there's been a few things we found like that. Guess hindsight is always 2020, when we now know that master branches can change and won't always be `master` as they were for years when that was originally written.
